export const browserCoreExamples = [
  "cortex browser status",
  "cortex browser start",
  "cortex browser stop",
  "cortex browser tabs",
  "cortex browser open https://example.com",
  "cortex browser focus abcd1234",
  "cortex browser close abcd1234",
  "cortex browser screenshot",
  "cortex browser screenshot --full-page",
  "cortex browser screenshot --ref 12",
  "cortex browser snapshot",
  "cortex browser snapshot --format aria --limit 200",
  "cortex browser snapshot --efficient",
  "cortex browser snapshot --labels",
];

export const browserActionExamples = [
  "cortex browser navigate https://example.com",
  "cortex browser resize 1280 720",
  "cortex browser click 12 --double",
  'cortex browser type 23 "hello" --submit',
  "cortex browser press Enter",
  "cortex browser hover 44",
  "cortex browser drag 10 11",
  "cortex browser select 9 OptionA OptionB",
  "cortex browser upload /tmp/openclaw/uploads/file.pdf",
  'cortex browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "cortex browser dialog --accept",
  'cortex browser wait --text "Done"',
  "cortex browser evaluate --fn '(el) => el.textContent' --ref 7",
  "cortex browser console --level error",
  "cortex browser pdf",
];
